export const FETCH_VOICES = 'FETCH_VOICES'
export const FETCH_VOICES_FAILURE = 'FETCH_VOICES_FAILURE'
export const FETCH_VOICES_SUCCESS = 'FETCH_VOICES_SUCCESS'

export const LIKE_VOICE = 'LIKE_VOICE'
export const DISLIKE_VOICE = 'DISLIKE_VOICE'

export const ADD_COMMENT = 'ADD_COMMENT'

export const SELECT_TAG = 'SELECT_TAG'