export const FETCH_VOICES = 'FETCH_VOICES'
export const FETCH_VOICES_PENDING = 'FETCH_VOICES_PENDING'
export const FETCH_VOICES_REJECTED = 'FETCH_VOICES_REJECTED'
export const FETCH_VOICES_FULFILLED = 'FETCH_VOICES_FULFILLED'

export const LIKE_VOICE = 'LIKE_VOICE'
export const DISLIKE_VOICE = 'DISLIKE_VOICE'
export const ADD_COMMENT = 'ADD_COMMENT'
export const SELECT_TAG = 'SELECT_TAG'

export const CREATE_NEW_VOICE = 'CREATE_NEW_VOICE'