export const FETCH_VOICES = 'FETCH_VOICES'
export const LIKE_VOICE = 'LIKE_VOICE'
export const DISLIKE_VOICE = 'DISLIKE_VOICE'
export const ADD_COMMENT = 'ADD_COMMENT'
export const SELECT_TAG = 'SELECT_TAG'